import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import './globals.css'
import { CommentProvider } from './context/CommentContext'
import { AuthProvider } from './context/AuthContext'

const rubik = Rubik({ subsets: ['latin'], weight: ['400', '500', '700'] })

export const metadata: Metadata = {
  title: 'Interactive Comments',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={rubik.className}>
        <AuthProvider>
          <CommentProvider>{children}</CommentProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
